### ISSUE TITLE
When set layout: 'bottomCenter', width: 600px; in custom css not work!!

### ISSUE THREAD

**Issue by jorgecroce** [needim/noty#260]
I need a noty layout "bottomCenter", but, I like a width of 600px. And not work!

Try this:

CSS:
        .someOtherTheme {
            overflow: hidden;
            border: 1px solid #fff;
            box-shadow: 2px 3px 5px rgba(0, 0, 0, 0.1);
            position: relative;
            width: 600px;
        }

JQuery:
       var n = noty({
            text:  'Hello World' ,
            type: 'information',
            timeout: 5000,
            maxVisible: 1,
            layout: 'bottomCenter',
            theme: 'someOtherTheme',
            animation   : {
                open  : 'animated pulse',
                close : 'animated flipOutX',
                easing: 'swing',
                speed : 500
            }
        });

**Comment by needim** [comment]
You need to override layout container styles.

```css
ul#noty_bottomCenter_layout_container {
  width: 600px !important
}

ul#noty_bottomCenter_layout_container li {
  width: 600px !important
}
```
