### ISSUE TITLE
Change width

### ISSUE THREAD

**Issue by alvarotrigo** [needim/noty#301]
Is it possible to change the message width? 

I'm currently doing it with CSS, but probably not the best solution:

``` css
#noty_topRight_layout_container{
    width: 36% !important;
}
#noty_topRight_layout_container li{
    width: 100% !important;
}
```
