### ISSUE TITLE
Notification moving on the screen

### ISSUE THREAD

**Issue by mtugnoli** [needim/noty#416]
Is it possible to move the notification around the screnn, like old windows save-screen ?

**Comment by needim** [comment]
Hi @mtugnoli, I'm not familiar with windows save-screen. Can you explain a little bit? Do you mean dragging notifications? If so, it's not possible.

**Comment by grantcarthew** [comment]
Looks like @mtugnoli is on extended holidays.

What he means is the notification box moves in x and y position one pixel at a time so the box moves diagonally till it hits an edge. Then it will bounce off the x or y side of the screen and continue.

Like this: http://78.media.tumblr.com/937d6e8e128a810b80986e27f913b51a/tumblr_nsbvx4dS911sd9dgjo1_540.gif

Seems like something that should be done by the consumer, not within Noty.

**Comment by needim** [comment]
Actually, it's possible with CSS animations. 

Reference: http://jsfiddle.net/tRV5h/

```css
#wrapper {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    height: 100%;
    width: 100%;
    margin: auto;
    background-color: red;
}
#ball {
    height: 50px;
    width: 50px;
    background: blue;
    border-radius: 50px;
    position: absolute;
    left: 0;
    animation: animate 10s linear 0s infinite;
}
@keyframes animate {
    0% { left: 0%; top: 50% }
    25% { left: 50%; top: 0% }
    50% { left: 100%; top: 50% }
    75% { left: 50%; top: 100% }
    100% { left: 0%; top: 50% }
}
```
